[[colors.indexed_colors]]
color = "0xffa066"
index = 16

[[colors.indexed_colors]]
color = "0xff5d62"
index = 17

[colors.bright]
black = "#575656"
red = "#EF5350"
green = "#22da6e"
yellow = "#ffeb95"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#7fdbca"
white = "#ffffff"

[colors.normal]
black = "#011627"
red = "#EF5350"
green = "#22da6e"
yellow = "#c5e478"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#21c7a8"
white = "#ffffff"

[colors.primary]
background = "#011627"
foreground = "#d6deeb"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "#22da6e"

[colors.search.matches]
foreground = "#000000"
background = "#22da6e"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
# family = "Hack Nerd Font Mono"
family = "GeistMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "GeistMono Nerd Font"
# family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
# family = "Hack Nerd Font Mono"
family = "GeistMono Nerd Font"
style = "Italic"

[font.normal]
# family = "Hack Nerd Font Mono"
family = "GeistMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 1
